### ISSUE TITLE
"deploying master branch" link is broken

### ISSUE THREAD

**Issue by paulirish** [zpnk/deploy.now#21]
i'm hovering over the "zpnk/stage-ci" link and you can see in the status bar that the link is broken

 <img width="670" alt="screen shot 2017-06-03 at 11 49 51 am" src="https://cloud.githubusercontent.com/assets/39191/26756256/dd3349d6-4852-11e7-8ce4-14f6a8629ffe.png">

**Comment by zpnk** [comment]
This was fixed in #19, but I didn't deploy after merging! 😞 Thanks for the report!
