### ISSUE TITLE
Better support for environment variables.

### ISSUE THREAD

**Issue by zpnk** [zpnk/deploy.now#3]
Right now any environment variables set in the url query can be removed in the ui. Chances are, if these envars have been placed in the url, they are required for the app to function properly. 

So any environment variables specified in the url should be considered required and not be removable.

Also, it would be cool to support pre-populating these envars, something like `?env[GREETING]=hello`.

**Comment by ericf** [comment]
> Also, it would be cool to support pre-populating these envars, something like `?env[GREETING]=hello`.

@zpnk did you ever end up support this?

**Comment by zpnk** [comment]
@ericf No, that has not been implemented yet.
